#!/bin/sh

global.hostname=sellwood
eth0.serverip=192.168.0.138

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp
global.dhcp.vendor_id=barebox-mx53-sellwood

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=nor
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=net

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-${global.hostname}.$rootfs_type

kernelimage=linuximage
#kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/${global.hostname}"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/home/reach/Ptxdist/projects/rootfs"
fi

autoboot_timeout=3

bootargs="console=ttymxc0,115200"

disk_parts="256k(barebox),128k(bareboxenv),4M(kernel),-(root)"
nor_parts="256k(barebox),128k(bareboxenv),3M(kernel)"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
